# Generated by Django 4.2.11 on 2024-04-16 10:39

import django.core.validators
from django.db import migrations, models
import world_of_speed.car_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=1, validators=[world_of_speed.car_app.validators.validate_year]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
