# Generated by Django 4.2.11 on 2024-04-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_car_year_alter_car_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image_url',
            new_name='image_URL',
        ),
    ]
